version: '3'

services:
 redis:
  image: redis
  ports:
   - "6379:6379"

 readstream:
  image: tareqz/python-redis-mystream
  depends_on:
   - redis
  environment:
   - REDISHOST=redis
   - REDISPORT=6379
   - REDISSTREAM=mystream
